"""Per-quote context paragraphs (English, up to 280 words each).

Keyed by timestamp_s, same as the CSV row identifier.
Generated by hand-grounded summarisation of the surrounding transcript.
"""

CONTEXTS: dict[int, str] = {}

# Opening, why communication is hard, fear of conflict, how anger masks fear (0:00 to 25:00)
CONTEXTS[52] = (
    "Chris opens by asking why people fear conflict so much. Jefferson answers that we've "
    "confused two things: aggression and strength. Most people grew up watching adults who "
    "treated yelling, intimidation and physical posturing as proof of being in control. The "
    "actual courage, he says, is staying calm in a hard moment and trusting that the "
    "conversation will end. Loudness isn't strength; it's the absence of capacity to hold "
    "discomfort."
)
CONTEXTS[95] = (
    "Building on the previous beat, Jefferson reframes anger as a defence mechanism. Underneath "
    "yelling and defensiveness there is almost always fear, fear of being misunderstood, "
    "fear of vulnerability, fear of not being enough. The point is not that fear is shameful, "
    "but that taking the lazy path of anger is a way to avoid the harder work of leaning "
    "across and actually engaging with what's underneath."
)
CONTEXTS[113] = (
    "Chris asks why people lose control so quickly in conversations. Jefferson's answer is "
    "physiological: yelling literally takes no effort. The fight-or-flight neuropathway is "
    "well-worn and instant. What requires real strength is interrupting that reflex, taking "
    "a breath, slowing down, and choosing your words. The slower response is the harder one, "
    "which is why most people skip it."
)
CONTEXTS[138] = (
    "After describing how a disagreement triggers the body the same way a physical threat does "
    "(pupils dilating, jaw clenching, breath held), Jefferson explains that this is also why "
    "facts rarely change minds. Once someone is biologically activated they're not processing "
    "evidence; they're defending an identity. How you made them feel matters more than what "
    "you proved."
)
CONTEXTS[171] = (
    "Chris pushes back on the popular 'facts don't care about your feelings' slogan, flipping "
    "it: in real conversations the opposite is true. Feelings completely override facts. "
    "Jefferson agrees, once emotion is in the room, no amount of data lands until the "
    "emotion is addressed."
)
CONTEXTS[225] = (
    "Jefferson uses the example of texting someone 'we need to talk.' The period at the end "
    "creates a vacuum: no context, no resolution, only the possibility that something is "
    "wrong. The listener's nervous system fills the gap with worst-case scenarios. Don't "
    "open hard topics with an open loop; either say more, or say nothing yet."
)
CONTEXTS[297] = (
    "Continuing on texting culture: the passive-aggressive sting of the thumbs-up reaction. "
    "Jefferson is emphatic, he'd rather be told to fuck off, because at least that's honest "
    "engagement. The thumbs-up signals 'I cared so little about you that I didn't even put "
    "an O in front of the K.' Indifference disguised as politeness."
)
CONTEXTS[360] = (
    "Chris offers his own framing: good emotional storytelling is the opposite of good "
    "dramatic storytelling. In a movie you save the twist for the end; in a hard conversation "
    "you put the reassurance up front. 'I'm not mad at you and this is nothing to be worried "
    "about' before any of the context, so the listener isn't drowning while you explain."
)
CONTEXTS[386] = (
    "Chris cites a line he recently learned from coach Connor Beaton: a script that opens a "
    "hard conversation by simultaneously naming the difficulty and the relationship's capacity "
    "for it. 'I know you can handle it, and I know we can handle it.' The framing primes the "
    "other person to lean in rather than brace."
)
CONTEXTS[450] = (
    "Jefferson contrasts two openings: small-talk-then-bombshell ('hey, you played pickleball "
    "lately?… so listen…') versus labelling the conversation up front. Naming the "
    "difficulty out loud actually lowers anxiety because it lets the other person ready "
    "themselves emotionally. 'This is going to be a hard conversation' is a gift, not a "
    "warning."
)
CONTEXTS[575] = (
    "They reference a famous Theo Vaughn / Sean Strickland clip. The MMA fighter is breaking "
    "down on the couch; Theo doesn't try to fix anything, doesn't ask questions, just says "
    "this. Jefferson and Chris call it the clearest example of space-holding they've ever "
    "seen, courage that looks like silence and presence."
)
CONTEXTS[529] = (
    "Chris breaks down the same Theo / Strickland clip in body-language terms. Theo doesn't "
    "stay solemn the whole time; he lobs a small joke that gives Strickland a chance to come "
    "up for air, then drops back into stillness when Strickland is ready to sink in again. "
    "Humour as breath, not as deflection."
)
CONTEXTS[767] = (
    "Chris quotes a line from Joe Hudson (his coach) that he says reframed how he relates to "
    "his partner. The fear in relationships is that your emotions will be 'too much' for the "
    "other person to hold. Saying out loud that there is room for all of it dissolves the "
    "instinct to shrink or perform."
)
CONTEXTS[824] = (
    "Jefferson extends Joe Hudson's idea into parenting. His eight-year-old came home upset "
    "about a school recess slight and started apologising for being upset. Jefferson tells "
    "his kids this line so they know misbehaviour, big feelings or failures don't threaten "
    "the relationship. Love is the container, not the reward."
)
CONTEXTS[916] = (
    "Chris asks Jefferson which lines he reaches for most. This is the one he says to his "
    "wife. It refuses the comfortable lie of brushing past something hard with 'we're fine.' "
    "If the relationship is the foundation, then nothing built on top of it works while it's "
    "cracked. He's saying: this is the first thing, not the last."
)
CONTEXTS[950] = (
    "Jefferson's elaboration on the previous quote. Sweeping a small grievance under the rug "
    "feels efficient in the moment (kids to bath, dinner to make, work to do) but each "
    "unaddressed micro-rupture becomes a paper cut, then a stack of paper cuts, then a wound "
    "that everyone forgot how it started."
)
CONTEXTS[961] = (
    "Another go-to line from Jefferson's marriage. When he notices he's reacting at a 7 to "
    "a level-3 situation, he doesn't bottle it and retreat. He invites his wife into it: "
    "'something else is coming up for me, I'm not sure yet.' The invitation itself is the "
    "connection, letting her see him mid-process rather than after he's wrapped it up."
)
CONTEXTS[1047] = (
    "After a beat on the vulnerability of asking for help, Jefferson offers this sharper "
    "framing of self-improvement. If your growth doesn't make you better in relation to "
    "anyone else (kids, partner, colleagues, friends) then it's not improvement, it's "
    "another form of self-absorption. Strengthening alone isn't strength."
)
CONTEXTS[1075] = (
    "Chris asks how to interrupt the body's escalation reflex in real time. Jefferson starts "
    "by puncturing a social-media myth: the brilliant comeback. Devastating zingers play "
    "well on TikTok but in real conversations they signal that you optimised for winning "
    "instead of staying. You don't get extra points; you usually lose ground."
)
CONTEXTS[1085] = (
    "Jefferson's signature technique, taught to every client before a deposition or cross-"
    "examination: take an audible breath before your first word. It does two things, it "
    "physically slows your nervous system, and it signals to the other party that you're "
    "not going to be rushed. This is the single most undervalued tool in heated conversation."
)
CONTEXTS[1100] = (
    "Sequel to the breath-first idea. The instinct in conflict is to match the other person's "
    "tempo, they speed up, you speed up. Jefferson reframes it: timing is something you "
    "own. You decide when the conversation happens, how fast it moves, and when it pauses. "
    "Don't let them set the rhythm."
)
CONTEXTS[1140] = (
    "Jefferson's example of using language to regulate yourself out loud. Naming your "
    "defensiveness is paradoxically the move that defuses it. By saying 'I can tell I'm "
    "getting defensive, I'll be better at this in a little bit' you both interrupt the "
    "escalation and give the other person something concrete to respect."
)
CONTEXTS[1157] = (
    "A variant of the previous: when you can feel the conversation is heavier than a quick "
    "response can handle. Asking for time isn't avoidance, it's a way of telling the other "
    "person that what they said matters enough that you don't want to fumble the reply. "
    "Slowness as respect."
)
CONTEXTS[1176] = (
    "Chris reflects back what Jefferson has been describing: even in disagreement, even in "
    "conflict, you're on the same side of the problem. Jefferson agrees, and adds that "
    "this is especially true when it's tense, that's exactly when most people forget it."
)
CONTEXTS[1289] = (
    "Jefferson references the research that the body needs roughly 20 minutes to come down "
    "from a flooded state. The common mistake is taking a two-minute timeout, walking back "
    "in, and immediately re-escalating because nothing has actually regulated. Real timeouts "
    "are longer than feel necessary."
)
CONTEXTS[1331] = (
    "Most people don't book time for the conversations that determine their relationships; "
    "they book time for the gym, the dentist, work. Jefferson argues the most important "
    "conversations deserve at least the same dignity. Asking for an hour next week to talk "
    "about something important is a powerful frame all by itself."
)
CONTEXTS[1368] = (
    "Chris shares a tactic from Dale Carnegie's 'How to Stop Worrying and Start Living': "
    "schedule your worry. Pick a specific window for it, Sunday at 2pm, say, and the rest "
    "of the week your brain can stop holding the worry in working memory because it knows "
    "there's a place for it."
)
CONTEXTS[1409] = (
    "Jefferson recommends writing out, before a hard conversation: what am I actually asking "
    "for? Do I want them to act, or just listen? What do I want to walk away with? Putting "
    "pen to paper exposes whether the conversation is even necessary, whether you're the "
    "right person to have it, and whether now is the right time."
)
CONTEXTS[1531] = (
    "Chris asks what anger usually hides. Jefferson recites a poem fragment he loves about "
    "sitting next to anger and discovering its real name is grief. Underneath rage is almost "
    "always loss, fear, or sadness that has no other language."
)
CONTEXTS[1559] = (
    "He extends the idea via a therapy saying: 'when it's hysterical, it's historical.' "
    "When someone's reaction is wildly out of proportion to the present moment, the present "
    "is just the trigger. The size of the emotion is being supplied by something older."
)
CONTEXTS[1567] = (
    "A small but important aside. Our emotions are intricate; our language for them is "
    "primitive, mad, sad, tired, fine. Jefferson points out that there's a whole vocabulary "
    "of finer-grained feeling words available, and using them changes what you can actually "
    "address in yourself and in someone else."
)
CONTEXTS[1726] = (
    "Chris frames anger as an evolutionary tool: before law enforcement, you needed an "
    "outsized response to deter further violations. That utility is mostly obsolete. Jefferson "
    "agrees and tightens the argument: pushing harder against someone you want to change is "
    "the surest way to entrench them in their position."
)

# Shame, boundaries, receiving aggression, passive-aggression (30:00 to 50:00)
CONTEXTS[1847] = (
    "Chris describes the pattern of girls being kicked out of nightclubs in Newcastle and "
    "moving rapidly from screaming injustice to tears. Jefferson generalises: shame works "
    "the same way. The defiance, the unfairness narrative, the indignation, all of it is "
    "the surface layer over self-loathing sadness that the person doesn't want anyone to see."
)
CONTEXTS[1923] = (
    "Chris asks about the biggest mistakes people make when they're on the receiving end of "
    "aggression. Jefferson sets up the central distinction he'll keep returning to. "
    "Assertiveness holds your line without discarding the relationship. Aggressiveness "
    "discards the relationship to hold the line. Same backbone, completely different stance."
)
CONTEXTS[1961] = (
    "Continuing the same answer. When someone hits you with a 7 in a 3-shaped conversation, "
    "they're having a conversation in their head you weren't invited to. The way out, "
    "Jefferson says, is to enter every conflict with the mindset of having something to learn "
    "rather than something to prove. Curiosity beats agreement."
)
CONTEXTS[1968] = (
    "Practical version of the previous: literally phrase the curiosity to yourself. Where is "
    "this reaction coming from? What might cause it? Jefferson uses this internal narration "
    "as a brake to stop himself from matching aggression with aggression in cross-"
    "examinations and in his own marriage."
)
CONTEXTS[1988] = (
    "The trap of the heated exchange. The moment you respond to someone's aggression in kind, "
    "you've validated their accusation about you. Whatever they said you were, you just "
    "proved. Their next move is to escalate. The only way to stay free of the trap is to not "
    "step into it in the first place."
)
CONTEXTS[2007] = (
    "Chris asks Jefferson how to set boundaries well. The most common failure, Jefferson says, "
    "is the all-bark, no-bite boundary. People announce a line but aren't willing to accept "
    "the consequence of enforcing it, so the line dissolves. A boundary you won't enforce "
    "isn't a boundary."
)
CONTEXTS[2021] = (
    "Jefferson gives his three-part template for conversational boundaries: one, what you "
    "will not do or accept; two, what happens if they continue; three, what you are willing "
    "to walk away from. Without all three pieces, you have a complaint, not a boundary."
)
CONTEXTS[2039] = (
    "Example application of the template. Notice the structure: behaviour-specific (not "
    "vague), conditional (names continuation), and ends with the actual exit. Jefferson "
    "stresses that you must be willing to actually get up and leave for the words to carry "
    "any weight."
)
CONTEXTS[2055] = (
    "A small linguistic shift Jefferson teaches. 'You can't yell at me' is a rule about them, "
    "which they'll fight. 'I don't respond to that volume' is a statement about you, which "
    "they can't argue with. It removes their target and leaves them with a behaviour to "
    "adjust if they want a response."
)
CONTEXTS[2068] = (
    "Closing the boundaries beat. Jefferson observes the inverse relationship between your "
    "composure and the aggressor's sense of control. The calmer you get, the more out of "
    "control they feel, because they were running on the assumption that they could push "
    "you into matching their energy."
)
CONTEXTS[2117] = (
    "Chris notes the awkward case: you're at a 3 and they're at a 7, and someone at a 7 "
    "doesn't want to be talked down by someone at a 3. Jefferson's resolution is the "
    "promise-of-return script. You take space without abandoning the conversation. The "
    "explicit re-engagement time is what makes it a pause and not a punishment."
)
CONTEXTS[2160] = (
    "They both bring up Chris Voss, the FBI negotiator. His signature move is labelling: "
    "reflecting back what you observe with a 'sounds like' or 'seems like.' Jefferson uses it "
    "constantly in depositions and at home. It invites the real thing out from under the "
    "surface remark without confrontation."
)
CONTEXTS[2269] = (
    "Chris asks how to deal with passive-aggressive people. Jefferson first explains the "
    "origin: passive-aggression is usually a childhood adaptation. The needs weren't safe to "
    "voice, so the person learned to indicate them sideways. 'What's coming up for you?' "
    "disarms the indirectness by inviting the real complaint into the open."
)
CONTEXTS[2300] = (
    "Same beat, a sharper variant. By naming the unspoken, you collapse the deniability that "
    "passive-aggression depends on. The other person has to either own what they meant or "
    "back off the indirect dig. Either way the move stops working."
)
CONTEXTS[2466] = (
    "Jefferson explains why passive-aggressive behaviour shows up so suddenly in adult "
    "conflict. We all carry old scripts from childhood. When something in the present makes "
    "you feel controlled, caged, or unsafe, your nervous system jumps back to the eight-"
    "year-old version of you that first felt it. You're not arguing with the person in front "
    "of you, you're arguing with an echo."
)
CONTEXTS[2569] = (
    "Chris asks Jefferson about delivering bad news. The frame Jefferson uses is the "
    "difference between nice and kind. Nice is performance: prioritise the surface comfort "
    "and lie about the truth. Kind is sacrifice: tell them the hard thing because you care "
    "enough to take the hit of saying it."
)
CONTEXTS[2596] = (
    "Within the bad-news answer, Jefferson warns against a common move: blaming them first to "
    "soften your own guilt about the news. 'If you hadn't done X, I wouldn't have to say "
    "this' is twisting the knife. Deliver the news clean, then sit in whatever comes next."
)
CONTEXTS[2631] = (
    "Closing the bad-news beat. The instinct to circle, hedge, and pad with kindness "
    "actually disrespects the listener. They know something's coming; making them wait longer "
    "is cruelty in nice clothes. Directness is the kinder option."
)
CONTEXTS[2670] = (
    "Chris asks how Jefferson would coach someone through breaking up with a partner. "
    "Assuming you've made the time and aren't doing it by text, the script is: label the "
    "hard conversation, then the verdict, in that order. No pleasantries first. Get to the "
    "point fast."
)
CONTEXTS[2722] = (
    "Specific anti-pattern in break-ups: the 'it's not you, it's me' move. It feels softer "
    "but it's also dishonest, and dishonesty is what poisons the long-term recovery from a "
    "break-up. Whatever the actual reason is, owning it produces cleaner closure than "
    "comforting yourself with a cliche."
)
CONTEXTS[2728] = (
    "Same template applied to firing an employee. 'This news is probably going to shock "
    "you, I need to let you go.' Then the gratitude, the kindness, the next steps. Verdict "
    "first because trying to thread compliments through the news erodes everyone's trust."
)
CONTEXTS[2780] = (
    "Chris brings up another communication tip he's picked up: when declining an invitation, "
    "lead with 'I can't make it.' Don't construct a fifty-second story about how hard things "
    "have been with the no buried at the end. The lead is the no, then the reason if you "
    "want to give one."
)
CONTEXTS[2796] = (
    "Jefferson agrees and adds the linguistic mechanism. Most people say 'I'd love to, but "
    "I can't.' The word 'but' deletes everything in front of it; the listener only hears the "
    "second clause. Reversing the order ('I can't make it. Thank you so much for the invite') "
    "keeps both pieces intact."
)
CONTEXTS[2833] = (
    "A throwaway Chris-line as they move on, but a real one. The compliment-criticism-"
    "compliment sandwich is taught in management courses, but in practice everyone sees "
    "through it. The praise reads as a setup for the punch, and the closing praise reads as "
    "an attempt to undo the punch. Neither lands."
)
CONTEXTS[2921] = (
    "Jefferson's mental model for hard conversations: a cold plunge. The dread before is "
    "worse than the doing. The first few seconds are a shock to the system. Then your body "
    "settles, you find clarity, and there's an end to it. Postponing the plunge keeps you in "
    "the dread permanently."
)
CONTEXTS[3052] = (
    "After observing that his ability to hold other people's emotion improved with practice, "
    "Jefferson distils a leadership principle. Whether you're a partner, a parent, or a "
    "manager, you have to learn to disappoint people on purpose. Sometimes care looks like "
    "the answer they didn't want to hear."
)
CONTEXTS[3117] = (
    "Chris references the parents of missing children who say 'we just want to know.' The "
    "open loop is worse than the verdict. Jefferson extends the principle to all hard "
    "deliveries: when you break up, fire, or refuse, give the reason. The closure is the "
    "kindness, even when the content is hard."
)
CONTEXTS[3137] = (
    "Jefferson sketches the difference between a 'nice guy' and a 'good man.' The nice guy "
    "softens the truth to avoid being disliked. The good man tells the truth because his "
    "values demand it, accepting the cost. Acting in alignment with what you actually believe "
    "is the upgrade."
)
CONTEXTS[3221] = (
    "Chris asks how empathetic people can avoid being overwhelmed by other people's "
    "emotions. Jefferson preserves empathy as a superpower but draws a line: feeling "
    "someone's emotion is different from carrying it. You don't have to absorb what wasn't "
    "handed to you. The image is of letting their feeling pass through rather than lodge in."
)
CONTEXTS[3252] = (
    "Concrete application of the empathy-overload idea. When you tell your in-laws they "
    "should stay at a hotel rather than your house, they may be hurt. That hurt is theirs to "
    "feel and theirs to do something with. Trying to manage their emotional response on top "
    "of your own boundary is what burns out empaths."
)
CONTEXTS[3319] = (
    "Reframe of people-pleasing. Jefferson is generous with the trait, it's a sign of "
    "consideration. The only failure mode is when you systematically leave yourself off the "
    "list of people you're trying to please. Include yourself, and people-pleasing becomes "
    "kindness with you in it."
)
CONTEXTS[3285] = (
    "Inside the same in-law example, Jefferson teaches a specific opener for self-advocacy: "
    "'I need to make sure that…' followed by the actual ask. No apology, no over-"
    "explanation, no hedge. 'I need' frames the request as legitimate without being "
    "aggressive."
)
CONTEXTS[3654] = (
    "After Chris reads his essay 'The Shame of Small Fears,' Jefferson lands on the line. "
    "We invest in our bodies but neglect what comes out of our mouths. A high-performance "
    "physique paired with low-skill communication is a Formula One car with no steering "
    "wheel. Pretty, fast, useless."
)
CONTEXTS[3721] = (
    "Chris notes that people spend years in misery to avoid a few minutes of pain. Jefferson "
    "lands the line as a near-quote. Silence is a choice with a guaranteed outcome. The "
    "result of an unhad conversation is the situation you're stuck in, and you're the one "
    "choosing to stay there."
)
CONTEXTS[3742] = (
    "Sister-line to the previous, from therapy. The breakthrough you keep waiting for lives "
    "inside the conversation you keep avoiding. Pain you flinch from is the location of the "
    "growth, not an obstacle to it."
)
CONTEXTS[3712] = (
    "Chris's framing of the asymmetry. People will sit inside years of low-grade misery, a "
    "bad job, a bad relationship, a bad apartment, to dodge a single hard conversation. The "
    "math is absurd once you state it, which is part of why stating it is useful."
)
CONTEXTS[3892] = (
    "After Jefferson talks about hidden metrics in family life (the unmeasurable quality of "
    "being present with your kid), Chris invokes the McNamara fallacy. The Vietnam war "
    "leadership measured what they could (combat deaths) instead of what mattered (domestic "
    "sentiment). The same inversion happens in personal lives: we optimise what we can track "
    "instead of what we'd actually choose if we could see it."
)

# Miscommunication, physiology, insults, lies (66:00 to 92:00)
CONTEXTS[4005] = (
    "Chris asks how to deal with someone who's not understanding you. Jefferson points at "
    "the foundational myth most people operate under. We assume our intended message lands "
    "intact, and that any failure is on the receiver. In practice, the gap between sent and "
    "received is enormous and constant, and pretending otherwise is the source of most "
    "argument loops."
)
CONTEXTS[4040] = (
    "Practical fix to the previous diagnosis. Instead of pushing back with 'that's not what "
    "I said', ask 'what did you hear?' The receiver describes the message they got. The gap "
    "becomes visible and addressable. Without this move, you keep louder-and-clearer-ing the "
    "same misunderstood sentence."
)
CONTEXTS[4065] = (
    "When the other person hears your concern and immediately offers fixes you didn't ask "
    "for, name the request. You're not asking for a solution. You're asking for the "
    "experience of being heard about something that matters to you. Saying this out loud "
    "saves the conversation from devolving into accidental problem-solving."
)
CONTEXTS[4086] = (
    "Within the same beat, Jefferson flags a signal. When someone hits you with 'you always' "
    "or 'you never,' they've left the present and are running an old tape. The argument they "
    "appear to be having with you is actually a montage of previous arguments, often with "
    "previous people. Spot it and you can stop trying to win the wrong fight."
)
CONTEXTS[4146] = (
    "Chris brings up research: above roughly 100 beats per minute, the prefrontal cortex "
    "goes offline. They watch a viral chart of a man's Fitbit heart rate during the moment "
    "his wife asked for a divorce, spiking to 150. The practical implication: when somebody "
    "is flooded, you are not negotiating with a reasoning system."
)
CONTEXTS[4435] = (
    "Chris asks how people should respond to an insult. Jefferson opens with the foundational "
    "move: silence. Five to seven full seconds of nothing. Most people fail this test because "
    "the silence feels like an eternity. The silence is the point. It hands the discomfort "
    "of what they just said back to them."
)
CONTEXTS[4471] = (
    "Continuing the same answer. The instinct in an insult is to volley, to send something "
    "back over the net. Jefferson rejects the framing entirely. It's not tennis. You don't "
    "have to catch what someone threw at you. You can let it lie there on the table where "
    "they put it."
)
CONTEXTS[4488] = (
    "Step two of Jefferson's insult-response protocol: ask them to say it again. 'I need you "
    "to repeat that.' He says he's almost never seen anyone successfully do it, because the "
    "ugly thing depended on the heat that powered it; repeated cold, in the spotlight, it "
    "becomes unbearable to the person who said it."
)
CONTEXTS[4555] = (
    "Jefferson generalises from his deposition work. Liars and manipulators feed on emotional "
    "reaction. They are not afraid of your anger; in some ways they want it, because it "
    "gives them more material to manipulate. What they cannot work with is your calm. Calm "
    "starves the dynamic they need."
)
CONTEXTS[4613] = (
    "Another insult response. Ask about intent: 'did you mean for that to sound as insulting "
    "as it did?' Most people retreat into qualifying ('well, I mean…') because owning the "
    "intent is uncomfortable. If they double down, you have clarity. Either way you've "
    "surfaced what's actually happening."
)
CONTEXTS[4914] = (
    "Jefferson shares a quieter, more powerful version of the same family of moves. In "
    "depositions when he's caught someone in a lie, he doesn't accuse. He says 'tell me what "
    "I'm missing.' The phrasing assumes good faith on the surface while creating space for "
    "the person to either come clean or contradict themselves further on record."
)
CONTEXTS[4978] = (
    "Tactical principle: when you're across from someone who will contradict any statement "
    "you make, switch to open questions. Statements give them something to push against. "
    "Open-ended where-questions force them to construct, which is where the contradictions "
    "appear."
)
CONTEXTS[5081] = (
    "Chris's image for the same dynamic: hand them rope and see what they do with it. Some "
    "people use it to climb out; some hang themselves. Either way, you've given them the "
    "agency and the consequence. You don't have to be the executioner."
)
CONTEXTS[5168] = (
    "Manipulators want speed: the immediate hit, the closed loop, the agreement they can "
    "weaponise later. Denying that closure is its own intervention. 'I'm going to need to "
    "come back to that later' is unsettling to someone whose tactic depends on you "
    "swallowing it now."
)
CONTEXTS[5213] = (
    "Chris asks about the British habit of pushing someone, then claiming 'only joking' when "
    "they react. Jefferson's preferred response, if you know the person, is a deadpan equal: "
    "'then I need you to be funnier.' It refuses the protective layer of the joke without "
    "matching the meanness."
)
CONTEXTS[5245] = (
    "If you don't know the person well and they hide behind 'just joking,' Jefferson uses "
    "this clearer line. It names what the remark actually was. The longer version: 'I know "
    "that wasn't a joke. It didn't sound like a joke. Sounds like an issue.' The fake-joke "
    "cover only works if you accept it."
)
CONTEXTS[5257] = (
    "Closing the insult-and-fake-joke section. Being the bigger person is not the same as "
    "taking it. It's choosing the response that requires more courage, not less. Backing "
    "off, refusing to escalate, naming what's happening, all of those need more nerve than "
    "matching the energy does."
)
CONTEXTS[5335] = (
    "Chris asks which phrases make people sound weak. Jefferson starts with 'I'm sorry but…' "
    "The construction signals that you're about to defend a position; the apology is a tax "
    "you pay to feel polite before doing it. Most listeners can tell, and the apology stops "
    "working."
)
CONTEXTS[5395] = (
    "Continuing the weak-phrases beat. 'I think' and 'I believe' are fine in casual talk, "
    "but in a setting where you want to be heard as confident, replace them with 'I'm "
    "confident that.' Tiny linguistic swap, large perceptual shift in how the listener "
    "calibrates your authority."
)
CONTEXTS[5481] = (
    "Chris asks where self-assurance comes from. Jefferson reverses the usual causality. "
    "Confidence isn't a feeling that produces assertive behaviour; it's the residue of "
    "assertive behaviour. You act, the feeling follows. Waiting to feel confident before "
    "acting is the trap."
)
CONTEXTS[5552] = (
    "Jefferson quotes his grandfather. Little dogs yip at everything because they have to. "
    "Big dogs bark once and the room knows. Confidence in conversation looks the same: not "
    "needing to comment on every passing thing, not having to defend every flank, trusting "
    "that you can speak less and still be felt."
)
CONTEXTS[5587] = (
    "Chris introduces Joe Hudson's concept of vagal authority. In any interaction, somebody's "
    "nervous system is dictating the room's temperature. The other parties move toward "
    "that person's regulation level. The question to ask when entering a meeting or a "
    "conversation: who has it, and what's it doing to the room?"
)
CONTEXTS[5678] = (
    "Jefferson's complementary frame, borrowed from sports: show up like you've been there "
    "before. Don't act surprised by the size of the moment. Composure is partly performance "
    "of capacity until the capacity catches up."
)
CONTEXTS[5763] = (
    "Closing the composure section. The most confident people in the room aren't the ones "
    "establishing their value. They're not name-dropping, not telling you what their company "
    "sold for, not showing off the car. They walk in with the big stick and don't need to "
    "say a word about it."
)
CONTEXTS[5872] = (
    "Jefferson refines his earlier 'good man vs nice guy' distinction. The nice guy is "
    "performing for approval; the good man is pursuing worth. The first is reactive to "
    "other people's perception, the second is anchored in his own values. The reorientation "
    "is from likability toward worthiness."
)
CONTEXTS[5908] = (
    "Jefferson's three-position spectrum, the clearest single frame in his whole toolkit. "
    "Aggression says 'I don't respect you.' Passivity says 'I don't respect me.' "
    "Assertiveness says 'I respect both of us.' Only one of the three keeps you and the "
    "relationship intact."
)
CONTEXTS[5933] = (
    "Jefferson recalls his father saying this to him as a kid. It's the model for boundary-"
    "setting that doesn't sever the bond. Discipline doesn't have to communicate withdrawal "
    "of love; it can communicate that love is large enough to include a limit."
)
CONTEXTS[5946] = (
    "Same idea, generalised. We tend to collapse love and limits into a binary: if I limit "
    "you I must be withdrawing care, if I care I must accept anything. Jefferson refuses the "
    "binary. Both things are true at once, and stating them both is the work."
)
CONTEXTS[6038] = (
    "Chris asks Jefferson about the assertive-asshole boundary. He observes that "
    "functionally, an asshole and an assertive person can produce similar outcomes (both "
    "state intent without apology). The difference is the orientation. The assertive person "
    "is considering the other party; the asshole is showing off."
)
CONTEXTS[6083] = (
    "Jefferson agrees and tightens it into a one-liner. The person who has to win every "
    "argument inevitably loses the relationships those arguments sit inside. Total record on "
    "the points, total loss on the actual game."
)
CONTEXTS[6105] = (
    "Chris asks Jefferson which of his ten practices for assertiveness people most often "
    "skip. His answer: being intentional with words. People conflate length with credibility, "
    "but the more words you need to explain a true thing, the more it starts to read like a "
    "lie. Brevity is a credibility move."
)
CONTEXTS[6253] = (
    "Jefferson uses the Cheesecake Factory menu as metaphor. Give people too many options or "
    "too much ambient information and they pick what they want to focus on, which is rarely "
    "what you meant. Meaning gets lost in volume."
)
CONTEXTS[6287] = (
    "Continuing the same point. Communication that depends on the listener guessing your "
    "intent is communication that will fail at scale. Clarity isn't about being curt; it's "
    "about not outsourcing your meaning to their interpretive work."
)
CONTEXTS[6302] = (
    "The closing summary of the word-economy section. Volume of words is not substance. "
    "Whole speeches can leave a room with nothing to hold; one sentence can. Track the "
    "actual signal you're transmitting, not the amount of air you're displacing."
)
CONTEXTS[6432] = (
    "Chris asks 'being right is overrated, what does that mean?' Jefferson's answer is the "
    "classic frame: do you want to be right or do you want to be happy? In silly arguments "
    "about movies it doesn't matter; in real arguments with people who matter, the choice "
    "is real and the cost of choosing 'right' is the relationship."
)
CONTEXTS[6485] = (
    "Continuing the same thread. You can keep winning arguments and still lose the "
    "relationship. The need to be right tends to be read by partners not as intellect but as "
    "insecurity. Nobody wants a partner who's keeping score."
)
CONTEXTS[6502] = (
    "Chris asks what to prioritise instead of being right. Jefferson's answer: appreciating "
    "the other person's perspective. He's careful to distinguish appreciation from "
    "agreement. You don't have to take on their view to honour the fact that they have one."
)
CONTEXTS[6515] = (
    "A specific linguistic move from the previous frame. 'I don't agree with that' is a "
    "comment on their point and invites defence. 'I see things differently' is a comment on "
    "your own perspective and doesn't attack theirs. Same disagreement, completely different "
    "atmosphere."
)
CONTEXTS[6555] = (
    "Jefferson on a common social-media posture. People love to declare that they cannot "
    "fathom how someone could hold a particular view. He pushes back: did you actually try? "
    "Have you asked them how they arrived there? Most of the time, no. The confusion is "
    "performative and cheap."
)
CONTEXTS[6839] = (
    "After Chris asks about lie-detection without evidence, Jefferson offers a behavioural "
    "tell. Truth-tellers can sit with being disbelieved. Liars cannot. Their internal stake "
    "in your belief is what gives them away; a disproportionate need for you to accept the "
    "story is the signal."
)
CONTEXTS[6862] = (
    "The same idea, sharpened to a single behaviour. The 'how dare you not believe me' "
    "response, the indignation, is the lie's tell. Real outrage at being doubted is much "
    "rarer than performative outrage covering for a lie."
)
CONTEXTS[6968] = (
    "Jefferson articulates the inner posture that makes you immune to manipulation tactics. "
    "Your access to your own truth doesn't depend on the other person's belief. You can let "
    "them disbelieve and still walk out with a clear conscience. The need to be believed is "
    "the leverage; remove it and the leverage disappears."
)
CONTEXTS[7074] = (
    "Chris asks what gold-standard repair looks like after an argument. Jefferson and his "
    "wife codified a three-step system. One, ownership without 'because you did X.' Two, "
    "acknowledgement of how you imagine the moment landed for them. Three, the explicit "
    "re-commit to being a team. All three matter; missing any one stalls the repair."
)
CONTEXTS[7118] = (
    "Inside the same answer, Jefferson elaborates step two of the repair: emotional steel-"
    "manning. Don't wait for them to articulate what they felt. Offer your best guess: 'I "
    "imagine that made you feel hurt, dismissed, less than.' Then let them correct you. The "
    "guess itself is the gift."
)
CONTEXTS[7193] = (
    "Chris quotes a line from Visakan Veerasamy: bad times are a far better predictor of "
    "relationship longevity than good times. The implication: peak moments don't save "
    "anything. The skill is rupture-and-repair, not adventure. People leave from too much "
    "unrepaired, not from too few peaks."
)
CONTEXTS[7238] = (
    "Jefferson agrees and rephrases it as a question to ask yourself about any relationship: "
    "how good are the bad times? The really hard conversations are not threats to the bond; "
    "they're invitations to deepen it. A relationship that can hold those grows; one that "
    "can't doesn't."
)
CONTEXTS[7263] = (
    "Sister-line to the previous. There's a floor in every long relationship that you only "
    "find by going through the hardest conversations, the 15-year knockdowns. Once you've "
    "touched the bottom together, you know how far up you can go. Without it, the ceiling "
    "is theoretical."
)
CONTEXTS[7338] = (
    "Chris asks what Jefferson has come to believe about choosing a partner. The answer is "
    "less romantic than expected. You need someone whose love is big enough to hold your "
    "worst moments, who doesn't punish you for them, but who also expects you to come out "
    "the other side and own what you did. Not 'good time' tolerance; ugly-moment tolerance."
)
CONTEXTS[7368] = (
    "Continuing the partner-choice answer. The healthy partner expects you to take "
    "responsibility for your bad moment, not blame them for it. 'That wasn't me at my best' "
    "is the line that earns the grace you were already given."
)
CONTEXTS[7552] = (
    "Chris asks what's most fascinating about being a trial lawyer that outsiders don't see. "
    "Jefferson describes the meta-conversation that runs alongside the legal one: body "
    "language, calm under bad evidence, selective objections. The most credible person in "
    "the room is often not the one with the best facts but the one whose presence reads as "
    "unbothered. Credibility is a posture, not a content."
)
CONTEXTS[7645] = (
    "Chris asks for the single most important principle of communication. Jefferson's "
    "answer: stop loading any single conversation with the weight of resolving the whole "
    "thing. We treat one conversation as decisive, which inflates the anxiety and the stakes. "
    "Most real change happens across a series."
)
CONTEXTS[7706] = (
    "Practical version of the previous. Reframe a big topic as a conversation that will "
    "take place over weeks. Saying 'I'd like to talk about this over the next month' lowers "
    "the anxiety for both people, because the moment is no longer a verdict. It's a chapter."
)
CONTEXTS[7766] = (
    "Closing the episode's main answer. Encourage the pursuit of perspective. Where did "
    "they learn it? How long have they held it? What hardship taught it? When you ask, "
    "people open up. You become the safe place where their view can be examined, not "
    "defended."
)
CONTEXTS[7772] = (
    "Same line, second formulation. The repeated framing is intentional: Jefferson wants "
    "perspective-pursuit to be the single transferable principle the listener walks out "
    "with. Hostility in disagreement evaporates when the other side believes you actually "
    "want to know how they got there."
)
CONTEXTS[7673] = (
    "In the closing answer, Jefferson contrasts pinning everything on one conversation with "
    "a calmer opener. Tell the person why you're bringing the topic up: because they matter. "
    "Tell them what the relationship will still be on the other side: still best friends, "
    "still going to dinner. The hard content rests on the unconditional ground."
)
